# Generated by Django 4.2.11 on 2026-03-19 10:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("unit", models.CharField(default="piece", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("online", "Online"),
                            ("kiosk", "Kiosk"),
                        ],
                        default="physical",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(db_index=True, max_length=50)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("wallet", "Digital Wallet"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("sold_at", models.DateTimeField(db_index=True)),
                ("sold_date", models.DateField(db_index=True)),
                ("sold_year", models.SmallIntegerField()),
                ("sold_month", models.SmallIntegerField()),
                ("sold_week", models.SmallIntegerField()),
                ("sold_dow", models.SmallIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="products.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="products.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-sold_at"],
                "indexes": [
                    models.Index(
                        fields=["sold_date", "product"],
                        name="products_sa_sold_da_5769ad_idx",
                    ),
                    models.Index(
                        fields=["sold_date", "store"],
                        name="products_sa_sold_da_6a0d6f_idx",
                    ),
                    models.Index(
                        fields=["sold_year", "sold_month"],
                        name="products_sa_sold_ye_54b450_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ForecastLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField(db_index=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("random_forest", "Random Forest"),
                            ("sarima", "SARIMA"),
                            ("ensemble", "Ensemble"),
                        ],
                        max_length=30,
                    ),
                ),
                ("predicted_qty", models.DecimalField(decimal_places=3, max_digits=10)),
                ("lower_bound", models.DecimalField(decimal_places=3, max_digits=10)),
                ("upper_bound", models.DecimalField(decimal_places=3, max_digits=10)),
                ("mae", models.FloatField(blank=True, null=True)),
                ("rmse", models.FloatField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="products.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="products.store",
                    ),
                ),
            ],
            options={
                "ordering": ["forecast_date"],
                "unique_together": {
                    ("product", "store", "forecast_date", "model_type")
                },
            },
        ),
    ]
